version: 2

jobs:
    checkout_code:
        docker:
            - image: circleci/python:3.6-stretch-node-browsers-legacy
        steps:
            - checkout
            - save_cache:
                key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - ~/project
            - run:
                name: echo pwd
                command: echo "$(pwd)"
                
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code