version: 2

jobs:
    checkout_code:
        docker:
            - image: circleci/python:3.6-stretch-node-browsers-legacy
        steps:
            - checkout
            - save_cache:
                key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - ~/project
    awscli_dependencies:
        docker:
            - image: circleci/python:3.6-stretch-node-browsers-legacy
        working_directory: ~/
        steps:
            - restore_cache:
                key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: list workfolder
                command: echo "$(ls -l)"
            - run:
                name: list project foler
                command: echo "$(ls project -l)"
            - run:
                name: setup dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r project/.circleci/requirements.txt
            - save_cache: # special step to save dependency cache
                key: awscli-{{ checksum "project/.circleci/requirements.txt" }}
                paths:
                    - "venv"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - awscli_dependencies:
            requires:
                - checkout_code